### ISSUE TITLE
Uploaded source map not linking due to js file name differences

### ISSUE THREAD

**Issue by johnnyoshika** [bugsnag/bugsnag-source-maps#55]
I'm trying to link my uploaded source map files to my React app errors that Bugsnag is capturing.

I'm using GitHub Actions for continuous deployment to deploy my Create React App project. The JavaScript file names it produces differs from when I run my build process locally.

For example, my deployed files are:

```
static/js/2.8e5de7fe.chunk.js
static/js/main.0abf3fdb.chunk.js
```

While my locally built files (using `react-scripts build`) are:

```
static/js/2.8ec2572f.chunk.js
static/js/2.8ec2572f.chunk.js.map
static/js/3.dfe9b29a.chunk.js
static/js/3.dfe9b29a.chunk.js.map
static/js/main.30c071e7.chunk.js
static/js/main.30c071e7.chunk.js.map
static/js/runtime-main.fb539f5c.js
static/js/runtime-main.fb539f5c.js.map
```

The source maps are being uploaded properly as they can be seen in the Bugsnag console:

![image](https://user-images.githubusercontent.com/504505/109393853-e1b5f700-78d8-11eb-84a4-bff846ab401d.png)

However, whenever an error is captured, it doesn't link to the source maps:

![image](https://user-images.githubusercontent.com/504505/109393884-0d38e180-78d9-11eb-8566-a03a1b4be2e0.png)

I tried this with and without setting appVersion. Here's the example where I do set the appVersion:

Notifier: 

```
  Bugsnag.start({
    apiKey,
    appVersion: '0.1.0',
    plugins: [new BugsnagPluginReact()],
  });
```

Source map upload:

```
const { browser } = require('@bugsnag/source-maps');

browser
  .uploadMultiple({
    apiKey,
    appVersion: '0.1.0',
    baseUrl: 'https://student.examind.io/static/js/',
    directory: 'build/static/js',
  })
```

When I tested without `appVersion`, I did exactly the same thing as above but with the `appVersion` property omitted.

How do I link my JavaScript files to the uploaded source maps if my CI tool produces different file names than the build I generate locally?

**Comment by johnnyoshika** [comment]
The solution turns out to be quite obvious now that I think about it. I ended up including the source map upload as part of my continuous deployment process.

When running `react-scripts build` with and without `GENERATE_SOURCEMAP=false`, the generated *.js file names are identical, so I build twice (once with source maps to sent to Bugsnag and once without). I could have just ran it once with generated source maps and then deleted the *.map files before deploying, but then I'd get a 404 source map errors when I opened dev tools.

Here's my final solution:

package.json:

```
  "scripts": {
       "build": "GENERATE_SOURCEMAP=false react-scripts build",
    "bugsnag": "react-scripts build && bugsnag-source-maps upload-browser ..."
  },
```

Github workflow file:

```
      - run: npm ci
      - run: npm run bugsnag
      - run: npm run build
```

**Comment by xander-jones** [comment]
👋. hey @johnnyoshika, thanks for sharing your solution with us. I don't believe `react-scripts` offers a method to generate maps _**and not**_ add the `sourceMappingURL`, it's an "all or nothing" situation, so your solution seems sensible to me so long as `react-scripts` continues to produce files of the same name using your method.

**Comment by abdulfatai360** [comment]
Hi @johnnyoshika,  Please I would love to know how you referenced your Bugsnag API key in the `bugsnag` script in your `package.json`

**Comment by johnnyoshika** [comment]
@abdulfatai360 I did it like this in package.json:

```
  "scripts": {
    ...
    "bugsnag": "react-scripts build && bugsnag-source-maps upload-browser --api-key $REACT_APP_BUGSNAG_API_KEY --app-version $REACT_APP_BUGSNAG_APP_VERSION ..."
    ...
  },
```

I use GitHub Actions for continuous deployment, so I store the API key in GitHub secrets, and inject it into the environment during deployment. The GitHub Action yml file looks something like this:

```
    env:
      REACT_APP_BUGSNAG_API_KEY: ${{secrets.REACT_APP_BUGSNAG_API_KEY}}
      REACT_APP_BUGSNAG_APP_VERSION: 0.1.${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm ci
      - run: npm run bugsnag
      ...etc...
```
