### ISSUE TITLE
Encoded URI for source URLs (Next.js)

### ISSUE THREAD

**Issue by macdonaldr93** [bugsnag/bugsnag-source-maps#57]
This is a specific problem with Next.js but I'm wondering how many others might be affected by this.

## Problem

When uploading source map URLs to Bugsnag, the URL uses characters that aren't encoded. For example, `*/_next/chunks/pages/posts/[id]/index-7bb752abed79eb3123b5.js`. When this URL gets loaded in the browser, it tries to match against `*/_next/chunks/pages/posts/%5Bid%5D/index-7bb752abed79eb3123b5.js`. The source map misses.

## Fix

This `url` should use `encodeURI` so properly escape characters like `[` so that URLs match.

**Comment by johnkiely1** [comment]
Hi @macdonaldr93, 

Thanks for raising, we will look into getting this resolved as soon as we can.

**Comment by macdonaldr93** [comment]
Conversation happening here: https://github.com/bugsnag/webpack-bugsnag-plugins/issues/51

I wasn't sure which repo had eyes on it so I posted in both haha
