### ISSUE TITLE
Can't get source maps to work due to delete before going production

### ISSUE THREAD

**Issue by witalobenicio** [bugsnag/bugsnag-source-maps#62]
### Describe the bug
My project was built with CRA and I've eject it afeter...I was trying to upload my map files using `BugsnagSourceMapUploaderPlugin` from `webpack-bugsnag-plugins`.
It seems to upload the chunk files, but doesn't get the map files. This may because I delete the .map files before sending the project to my server.
The same occurs if I try to use the command to upload multiple,

There is some way to still get the map files to work in bugsnag but delete them from production env?

### Environment
* Uploading for:
	* [X] Browser
	* [ ] Node
		* Node version:
	* [ ] React Native
		* React Native version:

**Comment by yousif-bugsnag** [comment]
Hi @witalobenicio,

I can see that you've also raised this via a support ticket - this appears to be a configuration issue, I've responded on that thread so closing this issue out to move the discussion there.
