### ISSUE TITLE
Staging builds for React Native

### ISSUE THREAD

**Issue by sidferreira** [bugsnag/bugsnag-source-maps#68]
We often use `staging` for some builds, but our builds go as `iOS, Release`... will it work if the stage is `staging`?

https://github.com/bugsnag/bugsnag-source-maps/blob/6d8338e17b07c7e4a57c15601302ef65f701ef55/src/uploaders/ReactNativeUploader.ts#L176

**Comment by mattdyoung** [comment]
Hi @sidferreira 

Yes, the source maps will be applied correctly regardless of what you set the [releaseStage](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#releasestage) to.

You can have many release stages for different development, test, staging and production environments but for each of those you'd deploy a React Native build which is either a development or release build i.e. the source maps only differ between development and release builds, not between different release stages.

When uploading your source maps you should specify `--dev` for development/debug builds only, not for release builds/variants:
https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#examples
