### ISSUE TITLE
Ignore query params when searching for a bundle file

### ISSUE THREAD

**Issue by Drodevbar** [bugsnag/bugsnag-source-maps#94]
### Description

Hello BugSnag team 👋 

I am having trouble setting up sourcemaps for a remix project that is being run via `remix-serve` (default remix server). The thing is that `remix-serve` by default [adds a query param while loading a file](https://github.com/remix-run/remix/blob/main/packages/remix-serve/cli.ts#L71), this in turn - as far as I understand - makes it impossible for BugSnag to load previously uploaded source maps.

The uploaded bundle file format is `index.js`, source map format is `index.js.map`. `index.js` has a proper reference to the map one at the end of the file - `//# sourceMappingURL=index.js.map`
However, due to the the addition of extra query param added by `remix-serve`, the file referenced in the error looks like below:
```bash
***/build/index.js?t=1711562424160.4358:1415:4
```

If my assumption that BugSnag doesn't allow for extra query params in the file name is true, do you consider adding support for that in the future?

**Describe the solution you'd like**

I would like BugSnag to allow wildcards/file patterns for bundle files while uploading the source maps. Alternatively, BugSnag could be looking for a bundle file ignoring query params.

**Describe alternatives you've considered**

N/A

**Additional context**

Fun fact: when I rename the bundle file to include some query param (let's say I name it `index.js?foo=bar`) and upload it like that (let's say via `bugsnag-source-maps upload-node` CLI), the UI shows the file without query param being presence (it's present as `index.js`). It suggests to me that query parameters shouldn't be taken into consideration while BugSnag is looking for a bundle file.

And yes, I have verified that uploaded source maps have the same `appVersion` as my notifier, so this is not the issue.

**Comment by Drodevbar** [comment]
It turned out this can be done using BugSnar REST upload API. The API allows you to specify `minifiedUrl` and it does support wildcards. Previously I was using the CLI and couldn't find that option. It might be reasonable to add the support for that to CLI too.

**Comment by Drodevbar** [comment]
It turned out this can be done using BugSnar REST upload API. The API allows you to specify `minifiedUrl` and it does support wildcards. Previously I was using the CLI and couldn't find that option. It might be reasonable to add the support for that to CLI as well.

**Comment by mclack** [comment]
Hi @Drodevbar 

Apologies for the delayed response on this.

It sounds like you've managed to find a workaround for this, but I'd like to make sure I understand the problem correctly to gauge whether there are any improvements we can make.

You mention that being able to supply a `minifiedUrl` when uploading your source maps resolved this issue for you, and that you couldn't find this option when using the [bugsnag-source-maps tool](https://docs.bugsnag.com/build-integrations/js/source-maps-browser/). The `minifiedUrl` parameter relates to the `--bundle-url` option that can be supplied when using the `upload-browser` command in the `bugsnag-source-maps` CLI: https://docs.bugsnag.com/build-integrations/js/source-maps-browser/#option-reference

Can I ask whether you've tried using `--bundle-url` with the `upload-browser` command when uploading source maps via the `bugsnag-source-maps` CLI? Does this work for you if you use the same `minifiedUrl` with wildcards here? You previously mentioned using the `upload-node` command, which should not require a `--bundle-url`, but it appears that Remix is a web framework, so perhaps you should be using the `upload-browser` command in the CLI instead?
